---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install packages.
      ansible.builtin.include_tasks: tasks/packages.yml

    - name: Configure vscode.
      ansible.builtin.include_tasks: tasks/vscode.yml

- ansible.builtin.import_playbook: "{{ playbook_dir }}/tasks/roles.yml"
