---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install packages.
      include_tasks: tasks/packages.yml

    - name: Configure vscode.
      include_tasks: tasks/vscode.yml

- import_playbook: "{{ playbook_dir }}/tasks/roles.yml"
