---
- name: Install packages using the systems package manager
  package:
    name: "{{ item }}"
    update_cache: true
    state: present
  become: yes
  with_items:
    - tmux
    - snapd
    - unzip

- name: Ensure the snap service is started
  service:
    name: snapd
    state: started
  become: yes
  tags:
    - molecule-notest

- name: Install packages using snap
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  become: yes
  with_items:
    - { name: code, classic: yes }
    - { name: doctl, classic: no }

- name: Install packages using pip3
  pip:
    name:
      - molecule
      - 'molecule-docker'
      - ansible-lint
      - yamllint
      - awscli
      - docker
    executable: pip3
    extra_args: --user

- name: Check if tfenv installed
  command: which tfenv
  changed_when: false
  failed_when: false
  register: tfenv_install
  
- name: Clone tfenv
  git:
    repo: https://github.com/tfutils/tfenv
    dest: "{{ ansible_user_dir }}/.tfenv"
  when: tfenv_install.rc != 0

- name: Add tfenv to $PATH
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export PATH="$HOME/.tfenv/bin:$PATH"'
    line: 'export PATH="$HOME/.tfenv/bin:$PATH"'
  when: tfenv_install.rc != 0
  
- name: Install terraform
  command: "{{ ansible_user_dir }}/.tfenv/bin/tfenv install"
  when: tfenv_install.rc != 0
  
