---
- hosts: all # noqa parser-error
  become: yes
  roles: # noqa parser-error
    - role: diodonfrost.terraform
    - role: geerlingguy.docker
      vars:
        docker_users: "{{ lookup('env','USER') }}"
      tags:
        - molecule-notest
    - role: huxoll.azure-cli
