---
- name: Install vscode extension
  ansible.builtin.command: "code --install-extension {{ item }}"
  become: no
  register: result
  with_items:
    - redhat.ansible
    - hashicorp.terraform
    - bbenoist.vagrant
    - amazonwebservices.aws-toolkit-vscode
    - ms-vscode.vscode-node-azure-pack
    - editorconfig.editorconfig
    - eamodio.gitlens
    - yzhang.markdown-all-in-one
    - ms-azuretools.vscode-docker
    - pkief.material-icon-theme
    - beardedbear.beardedtheme
    - aaron-bond.better-comments
    - ClemensPeters.format-json
  changed_when:
    - result.stdout is not search('is already installed.')
    - (result.stdout is search('hashicorp')) and False
  tags:
    - molecule-notest

- name: Apply vscode settings
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/settings.json"
    dest: $HOME/.config/Code/User/settings.json
    backup: true
